<a href="https://colab.research.google.com/github/Devil-92/100_Days_of_ML/blob/main/DataWrangling2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

## Reshaping and Pivoting

### Reshaping with Heirarchical Indexing

In [2]:
data = pd.DataFrame(np.arange(6).reshape((2, 3)) ,
                    index = pd.Index(['Ohio', 'Colorado'], name = 'state') ,
                    columns = pd.Index(['one', 'two', 'three'], name = 'number'))

In [3]:
data

number    one  two  three
state
Ohio        0    1      2
Colorado    3    4      5

In [4]:
result = data.stack()

In [5]:
result

state     number
Ohio      one       0
          two       1
          three     2
Colorado  one       3
          two       4
          three     5
dtype: int64

In [6]:
result.unstack()

number    one  two  three
state
Ohio        0    1      2
Colorado    3    4      5

In [7]:
print("We can also unstack using levels")

We can also unstack using levels

In [8]:
result.unstack(level = 0)

state   Ohio  Colorado
number
one        0         3
two        1         4
three      2         5

In [9]:
result.unstack(level = 1)

number    one  two  three
state
Ohio        0    1      2
Colorado    3    4      5

In [10]:
result.unstack(level = 'state')

state   Ohio  Colorado
number
one        0         3
two        1         4
three      2         5

In [11]:
print('Unstacking might introduce missing data if all values are not present')

Unstacking might introduce missing data if all values are not present

In [12]:
s1 = pd.Series([0 , 1 , 2 , 3] , index = ['a' , 'b' , 'c' , 'd'] , dtype = 'Int64')

In [13]:
s2 = pd.Series([4 , 5 , 6] , index = ['c' , 'd' , 'e'] , dtype = 'Int64')

In [14]:
d = pd.concat([s1 , s2] , keys = ['one' , 'two'])

In [15]:
d

one  a    0
     b    1
     c    2
     d    3
two  c    4
     d    5
     e    6
dtype: Int64

In [16]:
d.unstack()

        a     b  c  d     e
one     0     1  2  3  <NA>
two  <NA>  <NA>  4  5     6

In [17]:
d.unstack().stack()

one  a    0
     b    1
     c    2
     d    3
two  c    4
     d    5
     e    6
dtype: Int64

In [18]:
d.unstack().stack(future_stack = True)

one  a       0
     b       1
     c       2
     d       3
     e    <NA>
two  a    <NA>
     b    <NA>
     c       4
     d       5
     e       6
dtype: Int64

In [19]:
df = pd.DataFrame({
    'left': result,
    'right': result + 5
}, columns = pd.Index(['left', 'right'], name = 'side'))

In [20]:
df

side             left  right
state    number
Ohio     one        0      5
         two        1      6
         three      2      7
Colorado one        3      8
         two        4      9
         three      5     10

In [21]:
df.unstack(level = 0)

side   left          right
state  Ohio Colorado  Ohio Colorado
number
one       0        3     5        8
two       1        4     6        9
three     2        5     7       10

In [22]:
df.unstack(level = 0).stack(level = 0 , future_stack = True)

state         Ohio  Colorado
number side
one    left      0         3
       right     5         8
two    left      1         4
       right     6         9
three  left      2         5
       right     7        10

In [23]:
print('Stack makes given level of column into row and Unstack makes given level of row into column')

Stack makes given level of column into row and Unstack makes given level of row into column

### Pivoting Long to Wide Format

In [24]:
link = "https://raw.githubusercontent.com/wesm/pydata-book/refs/heads/3rd-edition/examples/macrodata.csv"

In [25]:
data = pd.read_csv(link)

In [26]:
data.head()

,year,quarter,realgdp,realcons,realinv,realgovt,realdpi,cpi,m1,tbilrate,unemp,pop,infl,realint
0,1959,1,2710.349,1707.4,286.898,470.045,1886.9,28.98,139.7,2.82,5.8,177.146,0.00,0.00
1,1959,2,2778.801,1733.7,310.859,481.301,1919.7,29.15,141.7,3.08,5.1,177.830,2.34,0.74
2,1959,3,2775.488,1751.8,289.226,491.260,1916.4,29.35,140.5,3.82,5.3,178.657,2.74,1.09
3,1959,4,2785.204,1753.7,299.356,484.052,1931.3,29.37,140.0,4.33,5.6,179.386,0.27,4.06
4,1960,1,2847.699,1770.5,331.722,462.199,1955.5,29.54,139.6,3.50,5.2,180.007,2.31,1.19

In [27]:
data = data.loc[ : , ['year' , 'quarter' , 'realgdp' , 'infl' , 'unemp']]

In [28]:
data.head()

   year  quarter   realgdp  infl  unemp
0  1959        1  2710.349  0.00    5.8
1  1959        2  2778.801  2.34    5.1
2  1959        3  2775.488  2.74    5.3
3  1959        4  2785.204  0.27    5.6
4  1960        1  2847.699  2.31    5.2

In [29]:
periods = pd.PeriodIndex(
    year=data.pop("year"),
    quarter=data.pop("quarter"),
    name = "date"
)

/tmp/ipykernel_24045/941785351.py:1: FutureWarning: Constructing PeriodIndex from fields is deprecated. Use PeriodIndex.from_fields instead.
  periods = pd.PeriodIndex(

In [30]:
periods

PeriodIndex(['1959Q1', '1959Q2', '1959Q3', '1959Q4', '1960Q1', '1960Q2',
             '1960Q3', '1960Q4', '1961Q1', '1961Q2',
             ...
             '2007Q2', '2007Q3', '2007Q4', '2008Q1', '2008Q2', '2008Q3',
             '2008Q4', '2009Q1', '2009Q2', '2009Q3'],
            dtype='period[Q-DEC]', name='date', length=203)

In [31]:
data.index = periods.to_timestamp('D')

In [32]:
data.head()

             realgdp  infl  unemp
date
1959-01-01  2710.349  0.00    5.8
1959-04-01  2778.801  2.34    5.1
1959-07-01  2775.488  2.74    5.3
1959-10-01  2785.204  0.27    5.6
1960-01-01  2847.699  2.31    5.2

In [33]:
data = data.reindex(columns = ['realgdp' , 'infl' , 'unemp'])

In [34]:
data.columns.name = 'item'

In [35]:
data.head()

item         realgdp  infl  unemp
date
1959-01-01  2710.349  0.00    5.8
1959-04-01  2778.801  2.34    5.1
1959-07-01  2775.488  2.74    5.3
1959-10-01  2785.204  0.27    5.6
1960-01-01  2847.699  2.31    5.2

In [36]:
long_data = (data.stack().reset_index().rename(columns = {0 : 'value'}))

In [37]:
long_data[:10]

        date     item     value
0 1959-01-01  realgdp  2710.349
1 1959-01-01     infl     0.000
2 1959-01-01    unemp     5.800
3 1959-04-01  realgdp  2778.801
4 1959-04-01     infl     2.340
5 1959-04-01    unemp     5.100
6 1959-07-01  realgdp  2775.488
7 1959-07-01     infl     2.740
8 1959-07-01    unemp     5.300
9 1959-10-01  realgdp  2785.204

In [38]:
print('The is called long format for multiple time series and each row in the table represents a single observation')

The is called long format for multiple time series and each row in the table represents a single observation

Data is frequently stored this way in relational SQL databases, as a **fixed schema** (column names and data types) allows the number of distinct values in the item column to change as data is added to the table.

In the previous example, date and item would usually be the **primary keys** (in relational database parlance), offering both:
* Relational integrity
* Easier joins

In some cases, the data may be more difficult to work with in this format; you might prefer to have a DataFrame containing **one column per distinct item value** indexed by timestamps in the date column.

In [39]:
pivoted = long_data.pivot(index = 'date' , columns = 'item' , values = 'value')

In [40]:
pivoted.head()

item        infl   realgdp  unemp
date
1959-01-01  0.00  2710.349    5.8
1959-04-01  2.34  2778.801    5.1
1959-07-01  2.74  2775.488    5.3
1959-10-01  0.27  2785.204    5.6
1960-01-01  2.31  2847.699    5.2

In [41]:
long_data['value_2'] = np.random.normal(0 , 1 , size = len(long_data))

In [42]:
long_data[:10]

        date     item     value   value_2
0 1959-01-01  realgdp  2710.349  0.891125
1 1959-01-01     infl     0.000  0.613935
2 1959-01-01    unemp     5.800 -0.986009
3 1959-04-01  realgdp  2778.801  0.482774
4 1959-04-01     infl     2.340 -0.185951
5 1959-04-01    unemp     5.100  1.063938
6 1959-07-01  realgdp  2775.488  0.135140
7 1959-07-01     infl     2.740 -0.118583
8 1959-07-01    unemp     5.300 -1.355124
9 1959-10-01  realgdp  2785.204 -0.573675

In [43]:
pivoted = long_data.pivot(index = 'date' , columns = 'item')

In [44]:
pivoted.head()

           value                   value_2
item        infl   realgdp unemp      infl   realgdp     unemp
date
1959-01-01  0.00  2710.349   5.8  0.613935  0.891125 -0.986009
1959-04-01  2.34  2778.801   5.1 -0.185951  0.482774  1.063938
1959-07-01  2.74  2775.488   5.3 -0.118583  0.135140 -1.355124
1959-10-01  0.27  2785.204   5.6  0.373440 -0.573675 -2.079400
1960-01-01  2.31  2847.699   5.2  1.911354 -0.436148  1.275067

In [45]:
print('Calling pivot is eqivalent to creating a heirarchical index using set_index followed by a call to unstack')

Calling pivot is eqivalent to creating a heirarchical index using set_index followed by a call to unstack

In [46]:
long_data.head()

        date     item     value   value_2
0 1959-01-01  realgdp  2710.349  0.891125
1 1959-01-01     infl     0.000  0.613935
2 1959-01-01    unemp     5.800 -0.986009
3 1959-04-01  realgdp  2778.801  0.482774
4 1959-04-01     infl     2.340 -0.185951

In [47]:
unstack = long_data.set_index(['date' , 'item']).unstack(level = 1)

In [48]:
unstack.head()

           value                   value_2
item        infl   realgdp unemp      infl   realgdp     unemp
date
1959-01-01  0.00  2710.349   5.8  0.613935  0.891125 -0.986009
1959-04-01  2.34  2778.801   5.1 -0.185951  0.482774  1.063938
1959-07-01  2.74  2775.488   5.3 -0.118583  0.135140 -1.355124
1959-10-01  0.27  2785.204   5.6  0.373440 -0.573675 -2.079400
1960-01-01  2.31  2847.699   5.2  1.911354 -0.436148  1.275067

### Pivoting Wide to Long Format

In [49]:
print('It is inverse of long to wide and done by melt inplace of pivot')

It is inverse of long to wide and done by melt inplace of pivot

In [50]:
print('Rather than transforming one column into many in a new df it merges many columns into one')

Rather than transforming one column into many in a new df it merges many columns into one

In [51]:
df = pd.DataFrame({
    'key': ['foo' , 'bar' , 'baz'] ,
    'A': [1 , 2 , 3] ,
    'B': [4 , 5 , 6] ,
    'C': [7 , 8 , 9]
})

In [52]:
df

   key  A  B  C
0  foo  1  4  7
1  bar  2  5  8
2  baz  3  6  9

In [53]:
print('We have to specify the group indicator and data values')

We have to specify the group indicator and data values

In [54]:
melted = pd.melt(df , id_vars = 'key')

In [55]:
melted

   key variable  value
0  foo        A      1
1  bar        A      2
2  baz        A      3
3  foo        B      4
4  bar        B      5
5  baz        B      6
6  foo        C      7
7  bar        C      8
8  baz        C      9

In [56]:
reshaped = melted.pivot(index = 'key' , columns = 'variable' , values = 'value')

In [57]:
reshaped

variable  A  B  C
key
bar       2  5  8
baz       3  6  9
foo       1  4  7

In [58]:
print('Since the pivot creates an index from the column used as row labels , we can use reset_index to move the data back into column')

Since the pivot creates an index from the column used as row labels , we can use reset_index to move the data back into column

In [59]:
reshaped.reset_index()

variable  key  A  B  C
0         bar  2  5  8
1         baz  3  6  9
2         foo  1  4  7

In [60]:
print('We can specify the subset of columns to use as val')

We can specify the subset of columns to use as val

In [61]:
pd.melt(df , id_vars = 'key' , value_vars = ['A' , 'B'])

   key variable  value
0  foo        A      1
1  bar        A      2
2  baz        A      3
3  foo        B      4
4  bar        B      5
5  baz        B      6

In [62]:
print("pandas.melt can be used without group identifiers")

pandas.melt can be used without group identifiers

In [63]:
pd.melt(df)

   variable value
0       key   foo
1       key   bar
2       key   baz
3         A     1
4         A     2
5         A     3
6         B     4
7         B     5
8         B     6
9         C     7
10        C     8
11        C     9

In [64]:
pd.melt(df , value_vars = ['A' , 'B' , 'C'])

  variable  value
0        A      1
1        A      2
2        A      3
3        B      4
4        B      5
5        B      6
6        C      7
7        C      8
8        C      9