<a href="https://colab.research.google.com/github/Devil-92/100_Days_of_ML/blob/main/DataCleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Handling Missing Values

### Intro

In [1]:
import pandas as pd
import numpy as np

In [2]:
float_data = pd.Series([1.2 , -3.5 , np.nan , 0])

In [3]:
float_data

0    1.2
1   -3.5
2    NaN
3    0.0
dtype: float64

In [4]:
float_data.isna()

0    False
1    False
2     True
3    False
dtype: bool

### Filtering out missing data

In [5]:
data = pd.Series([np.nan , 'Hi' , None , 'Another'])

In [6]:
data

0        NaN
1         Hi
2       None
3    Another
dtype: object

In [7]:
data.isna()

0     True
1    False
2     True
3    False
dtype: bool

In [8]:
data.notna()

0    False
1     True
2    False
3     True
dtype: bool

In [9]:
data[data.notna()]

1         Hi
3    Another
dtype: object

In [10]:
data.dropna()

1         Hi
3    Another
dtype: object

In [11]:
data

0        NaN
1         Hi
2       None
3    Another
dtype: object

In [12]:
print('The not nan values can be seen by either using notna and boolian indexing or dropna')

The not nan values can be seen by either using notna and boolian indexing or dropna

In [13]:
print('For Dataframe there are many ways to drop the columns and rows')

For Dataframe there are many ways to drop the columns and rows

In [14]:
print('Default dropna in df drops the row containing a missing value')

Default dropna in df drops the row containing a missing value

In [15]:
data = pd.DataFrame([[1 , 3 , 4] , [1 , np.nan , np.nan ] , [np.nan , np.nan , np.nan] , [np.nan , 4.4 , 3]])

In [16]:
data

     0    1    2
0  1.0  3.0  4.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  4.4  3.0

In [17]:
data.dropna()

     0    1    2
0  1.0  3.0  4.0

In [18]:
data.dropna(how = 'all')

     0    1    2
0  1.0  3.0  4.0
1  1.0  NaN  NaN
3  NaN  4.4  3.0

In [19]:
data.dropna(how = 'any')

     0    1    2
0  1.0  3.0  4.0

In [20]:
data[4] = np.nan

In [21]:
data

     0    1    2   4
0  1.0  3.0  4.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  4.4  3.0 NaN

In [22]:
data.dropna(axis = 1 , how = 'all')

     0    1    2
0  1.0  3.0  4.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  4.4  3.0

In [23]:
df = pd.DataFrame(np.random.standard_normal((7 , 3)))

In [24]:
df

          0         1         2
0  1.431036 -1.640953  0.215809
1 -0.666856  0.401445  0.459213
2 -0.984569  0.457628  0.322510
3 -0.579865 -1.270125  0.975513
4 -1.906196  0.975158  1.340270
5  0.755220  0.650364 -0.086603
6 -0.565380  1.268584  1.214266

In [25]:
df.iloc[:4 , 1] = np.nan

In [26]:
df.iloc[:2 , 2] = np.nan

In [27]:
df

          0         1         2
0  1.431036       NaN       NaN
1 -0.666856       NaN       NaN
2 -0.984569       NaN  0.322510
3 -0.579865       NaN  0.975513
4 -1.906196  0.975158  1.340270
5  0.755220  0.650364 -0.086603
6 -0.565380  1.268584  1.214266

In [28]:
df.dropna()

          0         1         2
4 -1.906196  0.975158  1.340270
5  0.755220  0.650364 -0.086603
6 -0.565380  1.268584  1.214266

In [29]:
df.dropna(thresh = 2)

          0         1         2
2 -0.984569       NaN  0.322510
3 -0.579865       NaN  0.975513
4 -1.906196  0.975158  1.340270
5  0.755220  0.650364 -0.086603
6 -0.565380  1.268584  1.214266

### Filling out missing data

In [30]:
df.fillna(0)

          0         1         2
0  1.431036  0.000000  0.000000
1 -0.666856  0.000000  0.000000
2 -0.984569  0.000000  0.322510
3 -0.579865  0.000000  0.975513
4 -1.906196  0.975158  1.340270
5  0.755220  0.650364 -0.086603
6 -0.565380  1.268584  1.214266

In [31]:
df.fillna({
    1 : 0.5 ,
    2 : 0
})

          0         1         2
0  1.431036  0.500000  0.000000
1 -0.666856  0.500000  0.000000
2 -0.984569  0.500000  0.322510
3 -0.579865  0.500000  0.975513
4 -1.906196  0.975158  1.340270
5  0.755220  0.650364 -0.086603
6 -0.565380  1.268584  1.214266

In [32]:
print('Dict enables to fill values according the the columns')

Dict enables to fill values according the the columns

In [33]:
df.fillna(method = 'ffill')

/tmp/ipykernel_66294/1145651979.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method = 'ffill')

          0         1         2
0  1.431036       NaN       NaN
1 -0.666856       NaN       NaN
2 -0.984569       NaN  0.322510
3 -0.579865       NaN  0.975513
4 -1.906196  0.975158  1.340270
5  0.755220  0.650364 -0.086603
6 -0.565380  1.268584  1.214266

In [34]:
df.ffill()

          0         1         2
0  1.431036       NaN       NaN
1 -0.666856       NaN       NaN
2 -0.984569       NaN  0.322510
3 -0.579865       NaN  0.975513
4 -1.906196  0.975158  1.340270
5  0.755220  0.650364 -0.086603
6 -0.565380  1.268584  1.214266

In [35]:
df.bfill(limit = 2)

          0         1         2
0  1.431036       NaN  0.322510
1 -0.666856       NaN  0.322510
2 -0.984569  0.975158  0.322510
3 -0.579865  0.975158  0.975513
4 -1.906196  0.975158  1.340270
5  0.755220  0.650364 -0.086603
6 -0.565380  1.268584  1.214266

In [36]:
df.fillna(df.mean(axis = 0))

          0         1         2
0  1.431036  0.964702  0.753191
1 -0.666856  0.964702  0.753191
2 -0.984569  0.964702  0.322510
3 -0.579865  0.964702  0.975513
4 -1.906196  0.975158  1.340270
5  0.755220  0.650364 -0.086603
6 -0.565380  1.268584  1.214266

In [37]:
df.fillna(df.mean(axis = 1))

          0         1         2
0  1.431036 -0.666856 -0.331030
1 -0.666856 -0.666856 -0.331030
2 -0.984569 -0.666856  0.322510
3 -0.579865 -0.666856  0.975513
4 -1.906196  0.975158  1.340270
5  0.755220  0.650364 -0.086603
6 -0.565380  1.268584  1.214266

In [38]:
df = pd.Series([1 , 2 , np.nan , 4])

In [39]:
df.interpolate()

0    1.0
1    2.0
2    3.0
3    4.0
dtype: float64

In [40]:
df.interpolate(method = 'polynomial' , order = 2)

0    1.0
1    2.0
2    3.0
3    4.0
dtype: float64

## Data Transformation

### Removing Duplicates

In [41]:
data = pd.DataFrame({
    'k1' : ['one' , 'two'] * 3 + ['two'] ,
    'k2' : [1 , 1 , 2 , 3 , 3 , 4 , 4]
})

In [42]:
data

    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [43]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [44]:
print('Duplicated returns true if the currect row is exactly same as any earlier row')

Duplicated returns true if the currect row is exactly same as any earlier row

In [45]:
data.drop_duplicates()

    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [46]:
data['v1'] = np.arange(7)

In [47]:
data

    k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [48]:
data.drop_duplicates(subset = ['k2'])

    k1  k2  v1
0  one   1   0
2  one   2   2
3  two   3   3
5  two   4   5

In [49]:
data.drop_duplicates(['k1'] , keep = 'last')

    k1  k2  v1
4  one   3   4
6  two   4   6

In [50]:
print("including keep = 'last' makes the whole process start from the last row")

including keep = 'last' makes the whole process start from the last row

### Transforming data using a Function or Mapping

In [51]:
data = pd.DataFrame({
    'Alpha' : ['A' , 'B' , 'C' , 'A' , 'D' , 'D' , 'A' , 'B' , 'C'] ,
    'Ounces' : np.arange(9)
})

In [52]:
data

  Alpha  Ounces
0     A       0
1     B       1
2     C       2
3     A       3
4     D       4
5     D       5
6     A       6
7     B       7
8     C       8

In [53]:
cap_to_small = {
    'A' : 'a' ,
    'B' : 'b' ,
    'C' : 'c' ,
    'D' : 'd'
}

In [54]:
data['Alpha_Small'] = data['Alpha'].map(cap_to_small)

In [55]:
data

  Alpha  Ounces Alpha_Small
0     A       0           a
1     B       1           b
2     C       2           c
3     A       3           a
4     D       4           d
5     D       5           d
6     A       6           a
7     B       7           b
8     C       8           c

In [56]:
def small_to_cap(x):
    return str(x).capitalize()

data['Alpha_Cap'] = data['Alpha_Small'].apply(small_to_cap)

In [57]:
data

  Alpha  Ounces Alpha_Small Alpha_Cap
0     A       0           a         A
1     B       1           b         B
2     C       2           c         C
3     A       3           a         A
4     D       4           d         D
5     D       5           d         D
6     A       6           a         A
7     B       7           b         B
8     C       8           c         C

### Replaceing Values

In [58]:
data = pd.Series([1 , -999 , 2 , -1000 , 2])

In [59]:
data

0       1
1    -999
2       2
3   -1000
4       2
dtype: int64

In [60]:
data.replace(-999 , np.nan)               # Replace a Single Value

0       1.0
1       NaN
2       2.0
3   -1000.0
4       2.0
dtype: float64

In [61]:
data.replace([-999 , -1000] , np.nan)       # Replace multiple Values

0    1.0
1    NaN
2    2.0
3    NaN
4    2.0
dtype: float64

In [62]:
data.replace([-999 , -1000] , [1 , 1])         # Replace multiple values with multiple Values

0    1
1    1
2    2
3    1
4    2
dtype: int64

In [63]:
data.replace({
    -999 : 1 ,
    -1000 : 1
})        # Passing a dict also works

0    1
1    1
2    2
3    1
4    2
dtype: int64

### Renaming Axis Indexes

In [64]:
data = pd.DataFrame(np.arange(12).reshape((3,4)) ,
                    index = ['abcde' , 'bcdef' , 'cdefg'] ,
                    columns = ['one' , 'two' , 'three' , 'four'])

In [65]:
data

       one  two  three  four
abcde    0    1      2     3
bcdef    4    5      6     7
cdefg    8    9     10    11

In [66]:
def transform(x) :
  return x[:3].upper()

In [67]:
data.index

Index(['abcde', 'bcdef', 'cdefg'], dtype='object')

In [68]:
data.index.map(transform)

Index(['ABC', 'BCD', 'CDE'], dtype='object')

In [69]:
data.index = data.index.map(transform)

In [70]:
data

     one  two  three  four
ABC    0    1      2     3
BCD    4    5      6     7
CDE    8    9     10    11

In [71]:
print('For visualizing a transformed index without modifing in place')

For visualizing a transformed index without modifing in place

In [72]:
data.rename(index = str.capitalize , columns = str.upper)

     ONE  TWO  THREE  FOUR
Abc    0    1      2     3
Bcd    4    5      6     7
Cde    8    9     10    11

In [73]:
print('rename also allows for custom passing of dict')

rename also allows for custom passing of dict

In [74]:
data.rename(index = {'ABC' : 'A'} , columns = {'one' : '1'})

     1  two  three  four
A    0    1      2     3
BCD  4    5      6     7
CDE  8    9     10    11

In [75]:
print('rename saves from the chore of copying the df manually and assigning new values to its index and column attributes')

rename saves from the chore of copying the df manually and assigning new values to its index and column attributes

### Discretization and Binning

In [76]:
rng = np.random.default_rng()

In [77]:
age = rng.integers(20 , 61 , size = 12)

In [78]:
age

array([29, 56, 52, 44, 40, 24, 51, 43, 33, 41, 50, 56])

In [79]:
age_cat = pd.cut(age , bins = 4)

In [80]:
age_cat

[(23.968, 32.0], (48.0, 56.0], (48.0, 56.0], (40.0, 48.0], (32.0, 40.0], ..., (40.0, 48.0], (32.0, 40.0], (40.0, 48.0], (48.0, 56.0], (48.0, 56.0]]
Length: 12
Categories (4, interval[float64, right]): [(23.968, 32.0] < (32.0, 40.0] < (40.0, 48.0] <
                                           (48.0, 56.0]]

In [81]:
age_cat.codes

array([0, 3, 3, 2, 1, 0, 3, 2, 1, 2, 3, 3], dtype=int8)

In [82]:
age_cat.categories

IntervalIndex([(23.968, 32.0], (32.0, 40.0], (40.0, 48.0], (48.0, 56.0]], dtype='interval[float64, right]')

In [83]:
age_cat.categories[2]

Interval(40.0, 48.0, closed='right')

In [84]:
pd.Series.value_counts(age_cat)

(48.0, 56.0]      5
(40.0, 48.0]      3
(32.0, 40.0]      2
(23.968, 32.0]    2
Name: count, dtype: int64

In [85]:
pd.cut(age , bins = 4 , right = False)

[[24.0, 32.0), [48.0, 56.032), [48.0, 56.032), [40.0, 48.0), [40.0, 48.0), ..., [40.0, 48.0), [32.0, 40.0), [40.0, 48.0), [48.0, 56.032), [48.0, 56.032)]
Length: 12
Categories (4, interval[float64, left]): [[24.0, 32.0) < [32.0, 40.0) < [40.0, 48.0) <
                                          [48.0, 56.032)]

In [86]:
age_group_names = ['a' , 'b' , 'c' , 'd']
pd.cut(age , bins = 4 , labels = age_group_names)

['a', 'd', 'd', 'c', 'b', ..., 'c', 'b', 'c', 'd', 'd']
Length: 12
Categories (4, object): ['a' < 'b' < 'c' < 'd']

In [87]:
data = np.random.uniform(size = 20)
data

array([0.54423435, 0.21456924, 0.86809503, 0.16670031, 0.83725957,
       0.83387238, 0.86501993, 0.70337107, 0.38851978, 0.86237118,
       0.249452  , 0.74665522, 0.28760935, 0.65483008, 0.28004406,
       0.53258338, 0.93933938, 0.58655919, 0.92670241, 0.02788046])

In [88]:
pd.cut(data , bins = 4 , precision = 2 , labels = ['1' , '2' , '3' , '4'])

['3', '1', '4', '1', '4', ..., '3', '4', '3', '4', '1']
Length: 20
Categories (4, object): ['1' < '2' < '3' < '4']

In [89]:
data = np.random.standard_normal(1000)

In [90]:
quartiles = pd.qcut(data , q = 4 , precision = 2)

In [91]:
quartiles

[(0.62, 2.69], (-3.3299999999999996, -0.76], (-0.76, -0.063], (-0.76, -0.063], (-0.76, -0.063], ..., (-0.76, -0.063], (-0.76, -0.063], (-0.063, 0.62], (0.62, 2.69], (-0.76, -0.063]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.3299999999999996, -0.76] < (-0.76, -0.063] < (-0.063, 0.62] <
                                           (0.62, 2.69]]

In [92]:
pd.Series.value_counts(quartiles)

(-3.3299999999999996, -0.76]    250
(-0.76, -0.063]                 250
(-0.063, 0.62]                  250
(0.62, 2.69]                    250
Name: count, dtype: int64

In [93]:
print('Default quartiles divide the datapoints into equal quartiles but we can specify our own quartiles')

Default quartiles divide the datapoints into equal quartiles but we can specify our own quartiles

In [94]:
pd.qcut(data , [0 , 0.1 , 0.5 , 0.9 , 1]).value_counts()

(-3.323, -1.334]     100
(-1.334, -0.0628]    400
(-0.0628, 1.204]     400
(1.204, 2.69]        100
Name: count, dtype: int64

### Detecting and Filtering Outliers

In [95]:
data = pd.DataFrame(np.random.standard_normal((1000 , 4)))
data.describe()

                 0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.002953     0.019088    -0.077722     0.031590
std       1.026345     0.987127     0.990654     0.988028
min      -3.643651    -3.212064    -3.275293    -3.177749
25%      -0.679732    -0.650470    -0.722805    -0.632316
50%      -0.014389     0.023751    -0.104562     0.045912
75%       0.713210     0.679590     0.580118     0.726825
max       2.806691     3.168961     3.532049     3.006951

In [96]:
col = data[2]

In [97]:
col[col.abs() > 3]

123   -3.268294
300    3.532049
969   -3.275293
Name: 2, dtype: float64

In [98]:
data[(data.abs() > 3).any(axis = 'columns')]

            0         1         2         3
37   1.316467 -0.091962 -0.677091  3.006951
123 -1.204753 -0.264748 -3.268294 -0.774466
268  1.032146 -0.213459 -0.020350 -3.177749
300 -0.620548 -0.970792  3.532049 -1.823216
356 -3.643651  0.809780  0.454889  0.914846
501 -3.077118  0.722496  1.626960  1.224131
898 -2.129179 -3.212064  0.486278 -1.932262
934  0.111117  3.168961 -2.175187  0.711288
969  1.419962  0.080532 -3.275293  2.104719

In [99]:
data[(data.abs() > 3)] = np.sign(data)*3

In [100]:
data.describe()

                 0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.002232     0.019132    -0.077710     0.031760
std       1.024030     0.985929     0.987171     0.987445
min      -3.000000    -3.000000    -3.000000    -3.000000
25%      -0.679732    -0.650470    -0.722805    -0.632316
50%      -0.014389     0.023751    -0.104562     0.045912
75%       0.713210     0.679590     0.580118     0.726825
max       2.806691     3.000000     3.000000     3.000000

In [101]:
np.sign(data).head()

     0    1    2    3
0  1.0  1.0 -1.0 -1.0
1 -1.0  1.0 -1.0  1.0
2  1.0  1.0 -1.0 -1.0
3 -1.0  1.0  1.0  1.0
4 -1.0  1.0  1.0  1.0

In [102]:
print('clip method can also be used')

clip method can also be used

In [103]:
data = data.clip(-2 , 2)

In [104]:
data.describe()

                 0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.000222     0.022392    -0.072967     0.034341
std       0.987989     0.954466     0.955557     0.955829
min      -2.000000    -2.000000    -2.000000    -2.000000
25%      -0.679732    -0.650470    -0.722805    -0.632316
50%      -0.014389     0.023751    -0.104562     0.045912
75%       0.713210     0.679590     0.580118     0.726825
max       2.000000     2.000000     2.000000     2.000000

### Permutation and Random Sampling

In [105]:
df = pd.DataFrame(np.arange(7*5).reshape((5 , 7)))
df

    0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
2  14  15  16  17  18  19  20
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34

In [106]:
sampler = np.random.permutation(5)

In [107]:
sampler

array([3, 0, 1, 2, 4])

In [108]:
df.take(sampler)

    0   1   2   3   4   5   6
3  21  22  23  24  25  26  27
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
2  14  15  16  17  18  19  20
4  28  29  30  31  32  33  34

In [109]:
df.iloc[sampler]

    0   1   2   3   4   5   6
3  21  22  23  24  25  26  27
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
2  14  15  16  17  18  19  20
4  28  29  30  31  32  33  34

In [110]:
column_sampler = np.random.permutation(7)
column_sampler

array([5, 0, 2, 4, 3, 6, 1])

In [111]:
df.take(column_sampler , axis = 1)

    5   0   2   4   3   6   1
0   5   0   2   4   3   6   1
1  12   7   9  11  10  13   8
2  19  14  16  18  17  20  15
3  26  21  23  25  24  27  22
4  33  28  30  32  31  34  29

In [112]:
df.iloc[ : , column_sampler]

    5   0   2   4   3   6   1
0   5   0   2   4   3   6   1
1  12   7   9  11  10  13   8
2  19  14  16  18  17  20  15
3  26  21  23  25  24  27  22
4  33  28  30  32  31  34  29

In [113]:
df.sample(n = 3)

    0   1   2   3   4   5   6
2  14  15  16  17  18  19  20
0   0   1   2   3   4   5   6
3  21  22  23  24  25  26  27

In [114]:
df.sample(n = 10 , replace = True)

    0   1   2   3   4   5   6
4  28  29  30  31  32  33  34
1   7   8   9  10  11  12  13
1   7   8   9  10  11  12  13
2  14  15  16  17  18  19  20
1   7   8   9  10  11  12  13
3  21  22  23  24  25  26  27
1   7   8   9  10  11  12  13
2  14  15  16  17  18  19  20
3  21  22  23  24  25  26  27
1   7   8   9  10  11  12  13

## Dummy Variables

In [115]:
print('Another type of transformation is statistical Modelling of a categorical variable into indicator or dummy matrix')

Another type of transformation is statistical Modelling of a categorical variable into indicator or dummy matrix

In [116]:
df = pd.DataFrame({
    'key' : ['b' , 'b' , 'a' , 'c' , 'a' , 'b'] ,
    'values' : np.arange(6)
})

In [117]:
df

  key  values
0   b       0
1   b       1
2   a       2
3   c       3
4   a       4
5   b       5

In [118]:
pd.get_dummies(df['key'])

       a      b      c
0  False   True  False
1  False   True  False
2   True  False  False
3  False  False   True
4   True  False  False
5  False   True  False

In [119]:
pd.get_dummies(df)

   values  key_a  key_b  key_c
0       0  False   True  False
1       1  False   True  False
2       2   True  False  False
3       3  False  False   True
4       4   True  False  False
5       5  False   True  False

In [120]:
pd.get_dummies(df['key'] , prefix = 'key')

   key_a  key_b  key_c
0  False   True  False
1  False   True  False
2   True  False  False
3  False  False   True
4   True  False  False
5  False   True  False

In [121]:
dummies = pd.get_dummies(df['key'] , prefix = 'key')

In [122]:
dummies

   key_a  key_b  key_c
0  False   True  False
1  False   True  False
2   True  False  False
3  False  False   True
4   True  False  False
5  False   True  False

In [123]:
df_with_dummies = df[['values']].join(dummies)

In [124]:
df_with_dummies

   values  key_a  key_b  key_c
0       0  False   True  False
1       1  False   True  False
2       2   True  False  False
3       3  False  False   True
4       4   True  False  False
5       5  False   True  False

In [125]:
movie_dataset_link = 'https://raw.githubusercontent.com/wesm/pydata-book/refs/heads/3rd-edition/datasets/movielens/movies.dat'

In [126]:
mnames = ['movie_id' , 'title' , 'genres']

In [127]:
movies = pd.read_table(movie_dataset_link , sep = '::' , header = None , names = mnames , engine = 'python')

In [128]:
movies.head()

   movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy

In [129]:
print('What if a single row of dataframe belongs ot multiple categories')

What if a single row of dataframe belongs ot multiple categories

In [130]:
dummies = movies['genres'].str.get_dummies('|')

In [131]:
dummies.head()

,Action,Adventure,Animation,Children's,Comedy,Crime,Documentary,Drama,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0
1,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0
2,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0
3,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0

In [132]:
dummies.sum(axis = 0)

Action          503
Adventure       283
Animation       105
Children's      251
Comedy         1200
Crime           211
Documentary     127
Drama          1603
Fantasy          68
Film-Noir        44
Horror          343
Musical         114
Mystery         106
Romance         471
Sci-Fi          276
Thriller        492
War             143
Western          68
dtype: int64

In [133]:
movies_windic = movies.join(dummies.add_prefix('Genre_'))

In [134]:
movies_windic.head(5)

,movie_id,title,genres,Genre_Action,Genre_Adventure,Genre_Animation,Genre_Children's,Genre_Comedy,Genre_Crime,Genre_Documentary,...,Genre_Fantasy,Genre_Film-Noir,Genre_Horror,Genre_Musical,Genre_Mystery,Genre_Romance,Genre_Sci-Fi,Genre_Thriller,Genre_War,Genre_Western
0,1,Toy Story (1995),Animation|Children's|Comedy,0,0,1,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2,Jumanji (1995),Adventure|Children's|Fantasy,0,1,0,1,0,0,0,...,1,0,0,0,0,0,0,0,0,0
2,3,Grumpier Old Men (1995),Comedy|Romance,0,0,0,0,1,0,0,...,0,0,0,0,0,1,0,0,0,0
3,4,Waiting to Exhale (1995),Comedy|Drama,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4,5,Father of the Bride Part II (1995),Comedy,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0

In [135]:
print('get_dummies for single category in a single row and str.get_dummies for multiple category in single row')

get_dummies for single category in a single row and str.get_dummies for multiple category in single row

In [136]:
print('We can do binning on a on pandas.get_dummies')

We can do binning on a on pandas.get_dummies

In [137]:
np.random.seed(42)

In [138]:
values = np.random.uniform(0 , 10 , size = 10)

In [139]:
values

array([3.74540119, 9.50714306, 7.31993942, 5.98658484, 1.5601864 ,
       1.5599452 , 0.58083612, 8.66176146, 6.01115012, 7.08072578])

In [140]:
bins = np.linspace(0 , 10 , 5)

In [141]:
bins

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [142]:
pd.get_dummies(pd.cut(values , bins))

   (0.0, 2.5]  (2.5, 5.0]  (5.0, 7.5]  (7.5, 10.0]
0       False        True       False        False
1       False       False       False         True
2       False       False        True        False
3       False       False        True        False
4        True       False       False        False
5        True       False       False        False
6        True       False       False        False
7       False       False       False         True
8       False       False        True        False
9       False       False        True        False