<a href="https://colab.research.google.com/github/Devil-92/100_Days_of_ML/blob/main/DataWrangling1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

## Heirarchical Indexing

### Introduction

In [2]:
data = pd.Series(np.random.uniform(0 , 1 , size = 7) , index = [['a' , 'a' , 'a' , 'b' , 'b' , 'c' , 'c'] , [1 , 2 , 3 , 1 , 2 , 1 , 4]])

In [3]:
data

a  1    0.023314
   2    0.627504
   3    0.143412
b  1    0.431844
   2    0.630615
c  1    0.709122
   4    0.799301
dtype: float64

In [4]:
data.index

MultiIndex([('a', 1),
            ('a', 2),
            ('a', 3),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 4)],
           )

In [5]:
data['b']

1    0.431844
2    0.630615
dtype: float64

In [6]:
print('This is a way of partial indexing')

This is a way of partial indexing

In [7]:
data['b' : 'c']

b  1    0.431844
   2    0.630615
c  1    0.709122
   4    0.799301
dtype: float64

In [8]:
data.loc[['b' , 'c']]

b  1    0.431844
   2    0.630615
c  1    0.709122
   4    0.799301
dtype: float64

In [9]:
data.iloc[6]

np.float64(0.7993013758788039)

In [10]:
data.loc[: , 2]             # Inner level selection

a    0.627504
b    0.630615
dtype: float64

In [11]:
data.unstack()

          1         2         3         4
a  0.023314  0.627504  0.143412       NaN
b  0.431844  0.630615       NaN       NaN
c  0.709122       NaN       NaN  0.799301

In [12]:
data.unstack().stack()

a  1    0.023314
   2    0.627504
   3    0.143412
b  1    0.431844
   2    0.630615
c  1    0.709122
   4    0.799301
dtype: float64

In [13]:
frame = pd.DataFrame(np.arange(12).reshape((4 , 3)) ,
                     index = [['a' , 'a' , 'b' , 'b'] , [1 , 2 , 1 , 2]] ,
                     columns = [['Delhi' , 'Delhi'  , 'Kolkata'] , ['Qutub Minar' , 'Taj Mahal' , 'Victoria']])

In [14]:
frame

          Delhi            Kolkata
    Qutub Minar Taj Mahal Victoria
a 1           0         1        2
  2           3         4        5
b 1           6         7        8
  2           9        10       11

In [15]:
frame.index

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [16]:
frame.index.names = ['key1' , 'key2']

In [17]:
frame.index.names

FrozenList(['key1', 'key2'])

In [18]:
frame.columns

MultiIndex([(  'Delhi', 'Qutub Minar'),
            (  'Delhi',   'Taj Mahal'),
            ('Kolkata',    'Victoria')],
           )

In [19]:
frame.columns.names = ['State' , 'Sites']

In [20]:
frame.columns.names

FrozenList(['State', 'Sites'])

In [21]:
frame

State           Delhi            Kolkata
Sites     Qutub Minar Taj Mahal Victoria
key1 key2
a    1              0         1        2
     2              3         4        5
b    1              6         7        8
     2              9        10       11

In [22]:
print('By this way we can set the names for hierarchical columns and rows')

By this way we can set the names for hierarchical columns and rows

In [23]:
frame.index.nlevels

2

In [24]:
frame.columns.nlevels

2

In [25]:
frame['Delhi']

Sites      Qutub Minar  Taj Mahal
key1 key2
a    1               0          1
     2               3          4
b    1               6          7
     2               9         10

In [26]:
frame['Kolkata']

Sites      Victoria
key1 key2
a    1            2
     2            5
b    1            8
     2           11

In [27]:
frame

State           Delhi            Kolkata
Sites     Qutub Minar Taj Mahal Victoria
key1 key2
a    1              0         1        2
     2              3         4        5
b    1              6         7        8
     2              9        10       11

In [28]:
frame.iloc[1 , :3]

State    Sites
Delhi    Qutub Minar    3
         Taj Mahal      4
Kolkata  Victoria       5
Name: (a, 2), dtype: int64

In [29]:
frame.iloc[: , 0]

key1  key2
a     1       0
      2       3
b     1       6
      2       9
Name: (Delhi, Qutub Minar), dtype: int64

### Reordering and Sorting Levels

In [30]:
print('swaplevel method takes two level numbers or names and returns a new object with levels interchanged')

swaplevel method takes two level numbers or names and returns a new object with levels interchanged

In [31]:
frame.swaplevel('key1' , 'key2')

State           Delhi            Kolkata
Sites     Qutub Minar Taj Mahal Victoria
key2 key1
1    a              0         1        2
2    a              3         4        5
1    b              6         7        8
2    b              9        10       11

In [32]:
print('sort_index by default sorts the data using all index levels but passing a single level or subset of levels sort that many level')

sort_index by default sorts the data using all index levels but passing a single level or subset of levels sort that many level

In [33]:
frame.sort_index(ascending = False)

State           Delhi            Kolkata
Sites     Qutub Minar Taj Mahal Victoria
key1 key2
b    2              9        10       11
     1              6         7        8
a    2              3         4        5
     1              0         1        2

In [34]:
frame.sort_index(level = 1)

State           Delhi            Kolkata
Sites     Qutub Minar Taj Mahal Victoria
key1 key2
a    1              0         1        2
b    1              6         7        8
a    2              3         4        5
b    2              9        10       11

In [35]:
frame.swaplevel(0 , 1).sort_index(level = 0)

State           Delhi            Kolkata
Sites     Qutub Minar Taj Mahal Victoria
key2 key1
1    a              0         1        2
     b              6         7        8
2    a              3         4        5
     b              9        10       11

In [36]:
print('for sorting use sort_index(level = x) and for reordering we use swaplevel')

for sorting use sort_index(level = x) and for reordering we use swaplevel

In [37]:
print('Data selection is better if the index is sorted lexographically and we it by calling sort_index')

Data selection is better if the index is sorted lexographically and we it by calling sort_index

### Summary Statistics by Level

In [38]:
frame

State           Delhi            Kolkata
Sites     Qutub Minar Taj Mahal Victoria
key1 key2
a    1              0         1        2
     2              3         4        5
b    1              6         7        8
     2              9        10       11

In [39]:
frame.groupby(level = 1).sum()

State       Delhi            Kolkata
Sites Qutub Minar Taj Mahal Victoria
key2
1               6         8       10
2              12        14       16

In [40]:
frame.groupby(level = 0).sum()

State       Delhi            Kolkata
Sites Qutub Minar Taj Mahal Victoria
key1
a               3         5        7
b              15        17       19

In [41]:
frame.groupby(level = 0 , axis = 1).sum()

/tmp/ipykernel_50113/2848016305.py:1: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  frame.groupby(level = 0 , axis = 1).sum()

State      Delhi  Kolkata
key1 key2
a    1         1        2
     2         7        5
b    1        13        8
     2        19       11

In [42]:
frame.T.groupby(level = 0).sum()

key1     a      b
key2     1  2   1   2
State
Delhi    1  7  13  19
Kolkata  2  5   8  11

In [43]:
frame.T.groupby(level = 1).sum()

key1         a     b
key2         1  2  1   2
Sites
Qutub Minar  0  3  6   9
Taj Mahal    1  4  7  10
Victoria     2  5  8  11

### Indexing with a DataFrame's columnns

In [44]:
frame = pd.DataFrame({
    'a' : range(7) ,
    'b' : range(6 , -1 , -1) ,
    'c' : ['A' , 'A' , 'A' , 'B' , 'B' , 'B' , 'B'] ,
    'd' : [0 , 1 , 2 , 0 , 1 , 2 , 3]
})

In [45]:
frame

   a  b  c  d
0  0  6  A  0
1  1  5  A  1
2  2  4  A  2
3  3  3  B  0
4  4  2  B  1
5  5  1  B  2
6  6  0  B  3

In [46]:
frame2 = frame.set_index(['c' , 'd'])

In [47]:
frame2

     a  b
c d
A 0  0  6
  1  1  5
  2  2  4
B 0  3  3
  1  4  2
  2  5  1
  3  6  0

In [48]:
print('We can keep the c and d columns by drop = False but by default they are dropped (drop = True)')

We can keep the c and d columns by drop = False but by default they are dropped (drop = True)

In [49]:
frame.set_index(['c' , 'd'] , drop = False)

     a  b  c  d
c d
A 0  0  6  A  0
  1  1  5  A  1
  2  2  4  A  2
B 0  3  3  B  0
  1  4  2  B  1
  2  5  1  B  2
  3  6  0  B  3

In [50]:
print('The opposite of set_index is reset_index , it makes the index move back to column')

The opposite of set_index is reset_index , it makes the index move back to column

In [51]:
frame2.reset_index()

   c  d  a  b
0  A  0  0  6
1  A  1  1  5
2  A  2  2  4
3  B  0  3  3
4  B  1  4  2
5  B  2  5  1
6  B  3  6  0

## Combining and Merging Datasets

In [52]:
print('Data contined in pandas objects can be combined in a number of ways')

Data contined in pandas objects can be combined in a number of ways

In [53]:
print('pandas.merge , pandas.concat , combine_first are some of them')

pandas.merge , pandas.concat , combine_first are some of them

### DataBase style DataFrame Joins

#### one to many join

In [54]:
df1 = pd.DataFrame({
    'key' : ['b' , 'b' , 'a' , 'c' , 'a' , 'a' , 'b'] ,
    'data1' : pd.Series(range(7))
})

In [55]:
df1

  key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   a      5
6   b      6

In [56]:
df2 = pd.DataFrame({
    'key' : ['a' , 'b' , 'd'] ,
    'data2' : pd.Series(range(3))
})

In [57]:
df2

  key  data2
0   a      0
1   b      1
2   d      2

In [58]:
pd.merge(df1 , df2)

  key  data1  data2
0   b      0      1
1   b      1      1
2   a      2      0
3   a      4      0
4   a      5      0
5   b      6      1

In [59]:
print('pd merges on overlapping column name as key but it is good to specify')

pd merges on overlapping column name as key but it is good to specify

In [60]:
pd.merge(df1 , df2 , on = 'key')

  key  data1  data2
0   b      0      1
1   b      1      1
2   a      2      0
3   a      4      0
4   a      5      0
5   b      6      1

In [61]:
print('If column names are different we can use left_on and right_on')

If column names are different we can use left_on and right_on

In [62]:
df3 = pd.DataFrame({
    'key1' : ['b' , 'b' , 'a' , 'c' , 'a' , 'a' , 'a'] ,
    'data1' : pd.Series(range(7))
})

In [63]:
df4 = pd.DataFrame({
    'key2' : ['a' , 'b' , 'd'] ,
    'data2' : pd.Series(range(3))
})

In [64]:
pd.merge(df3 , df4 , left_on = 'key1' , right_on = 'key2')

  key1  data1 key2  data2
0    b      0    b      1
1    b      1    b      1
2    a      2    a      0
3    a      4    a      0
4    a      5    a      0
5    a      6    a      0

In [65]:
pd.merge(df1 , df2 , how = 'outer')

  key  data1  data2
0   a    2.0    0.0
1   a    4.0    0.0
2   a    5.0    0.0
3   b    0.0    1.0
4   b    1.0    1.0
5   b    6.0    1.0
6   c    3.0    NaN
7   d    NaN    2.0

In [66]:
print('By defult the merge have inner join')

By defult the merge have inner join

In [67]:
pd.merge(df3 , df4 , left_on = 'key1' , right_on = 'key2' , how = 'outer')

  key1  data1 key2  data2
0    a    2.0    a    0.0
1    a    4.0    a    0.0
2    a    5.0    a    0.0
3    a    6.0    a    0.0
4    b    0.0    b    1.0
5    b    1.0    b    1.0
6    c    3.0  NaN    NaN
7  NaN    NaN    d    2.0

In [68]:
print('Types of argument in how - inner , outer , right , left')

Types of argument in how - inner , outer , right , left

#### Many to many

In [69]:
df1 = pd.DataFrame({
    'key' : ['b' , 'b' , 'a' , 'c' , 'a' , 'b'] ,
    'data1' : pd.Series(range(6) , dtype = 'Int64')
})

In [70]:
df2 = pd.DataFrame({
    'key' : ['a' , 'b' , 'a' , 'b' , 'd'] ,
    'data2' : pd.Series(range(5) , dtype = 'Int64')
})

In [71]:
df1

  key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [72]:
df2

  key  data2
0   a      0
1   b      1
2   a      2
3   b      3
4   d      4

In [73]:
pd.merge(df1 , df2 , on = 'key' , how = 'left')

   key  data1  data2
0    b      0      1
1    b      0      3
2    b      1      1
3    b      1      3
4    a      2      0
5    a      2      2
6    c      3   <NA>
7    a      4      0
8    a      4      2
9    b      5      1
10   b      5      3

In [74]:
pd.merge(df1 , df2 , how = 'inner')

  key  data1  data2
0   b      0      1
1   b      0      3
2   b      1      1
3   b      1      3
4   a      2      0
5   a      2      2
6   a      4      0
7   a      4      2
8   b      5      1
9   b      5      3

In [75]:
l = pd.DataFrame({
    'key1' : ['foo' , 'foo' , 'bar'] ,
    'key2' : ['one' , 'two' , 'one'] ,
    'lval' : pd.Series([1 , 2 , 3] , dtype = 'Int64')
})

In [76]:
l

  key1 key2  lval
0  foo  one     1
1  foo  two     2
2  bar  one     3

In [77]:
r = pd.DataFrame({
    'key1' : ['foo' , 'foo' , 'bar' , 'bar'] ,
    'key2' : ['one' , 'one' , 'one' , 'two'] ,
    'rval' : pd.Series([4 , 5 , 6 , 7] , dtype = 'Int64')
})

In [78]:
r

  key1 key2  rval
0  foo  one     4
1  foo  one     5
2  bar  one     6
3  bar  two     7

In [79]:
pd.merge(l , r , on = ['key1' , 'key2'] , how = 'outer')

  key1 key2  lval  rval
0  bar  one     3     6
1  bar  two  <NA>     7
2  foo  one     1     4
3  foo  one     1     5
4  foo  two     2  <NA>

In [80]:
print('For overlapping column names like :')

For overlapping column names like :

In [81]:
pd.merge(l , r , on = 'key1')

  key1 key2_x  lval key2_y  rval
0  foo    one     1    one     4
1  foo    one     1    one     5
2  foo    two     2    one     4
3  foo    two     2    one     5
4  bar    one     3    one     6
5  bar    one     3    two     7

In [82]:
pd.merge(r , l , on = 'key1')

  key1 key2_x  rval key2_y  lval
0  foo    one     4    one     1
1  foo    one     4    two     2
2  foo    one     5    one     1
3  foo    one     5    two     2
4  bar    one     6    one     3
5  bar    two     7    one     3

In [83]:
pd.merge(l , r , on = 'key2')

  key1_x key2  lval key1_y  rval
0    foo  one     1    foo     4
1    foo  one     1    foo     5
2    foo  one     1    bar     6
3    foo  two     2    bar     7
4    bar  one     3    foo     4
5    bar  one     3    foo     5
6    bar  one     3    bar     6

In [84]:
pd.merge(r , l , on = 'key2')

  key1_x key2  rval key1_y  lval
0    foo  one     4    foo     1
1    foo  one     4    bar     3
2    foo  one     5    foo     1
3    foo  one     5    bar     3
4    bar  one     6    foo     1
5    bar  one     6    bar     3
6    bar  two     7    foo     2

In [85]:
print('We can change the suffix using the suffices option')

We can change the suffix using the suffices option

In [86]:
pd.merge(l , r , on = 'key1' , suffixes = ('_left' , '_right'))

  key1 key2_left  lval key2_right  rval
0  foo       one     1        one     4
1  foo       one     1        one     5
2  foo       two     2        one     4
3  foo       two     2        one     5
4  bar       one     3        one     6
5  bar       one     3        two     7

#### Merging on Index

In [87]:
l1 = pd.DataFrame({
    "key" : ['a' , 'b' , 'a' , 'a' , 'b' , 'c'] ,
    'value' : pd.Series(range(6) , dtype = 'Int64')
})
l1

  key  value
0   a      0
1   b      1
2   a      2
3   a      3
4   b      4
5   c      5

In [88]:
r1 = pd.DataFrame({
    'group_val' : [3.5 , 7]
} , index = ['a' , 'b'])

In [89]:
r1

   group_val
a        3.5
b        7.0

In [90]:
pd.merge(l1 , r1 , left_on = 'key' , right_index = True)

  key  value  group_val
0   a      0        3.5
1   b      1        7.0
2   a      2        3.5
3   a      3        3.5
4   b      4        7.0

In [91]:
print('This is an example of many to one merge')

This is an example of many to one merge

In [92]:
pd.merge(l1 , r1 , left_on = 'key' , right_index = True , how = 'outer')

  key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0
5   c      5        NaN

In [93]:
lefth = pd.DataFrame({
    'key1' : ['A' , 'A' , 'A' , 'B' , 'B'] ,
    'key2' : [2000 , 2001 , 2002 , 2001 , 2002] ,
    'data' : pd.Series(range(5) , dtype = 'Int64')
})

In [94]:
righth_index = pd.MultiIndex.from_arrays(
    [
        ['B' , 'B' , 'A' , 'A' , 'A' , 'A'] ,
        [2001 , 2000 , 2000 , 2000 , 2001 , 2002]
    ]
)

In [95]:
righth = pd.DataFrame({
    'event1' : pd.Series([0 , 2 , 4 , 6 , 8 , 10] , dtype = 'Int64' , index = righth_index) ,
    'event2' : pd.Series([1 , 3 , 5 , 7 , 9 , 11] , dtype = 'Int64' , index = righth_index)
})

In [96]:
lefth

  key1  key2  data
0    A  2000     0
1    A  2001     1
2    A  2002     2
3    B  2001     3
4    B  2002     4

In [97]:
righth

        event1  event2
B 2001       0       1
  2000       2       3
A 2000       4       5
  2000       6       7
  2001       8       9
  2002      10      11

In [98]:
pd.merge(lefth , righth , left_on = ['key1' , 'key2'] , right_index = True)

  key1  key2  data  event1  event2
0    A  2000     0       4       5
0    A  2000     0       6       7
1    A  2001     1       8       9
2    A  2002     2      10      11
3    B  2001     3       0       1

In [99]:
pd.merge(lefth , righth , how = 'outer' , left_on = ['key1' , 'key2'] , right_index = True)

  key1  key2  data  event1  event2
0    A  2000     0       4       5
0    A  2000     0       6       7
1    A  2001     1       8       9
2    A  2002     2      10      11
4    B  2000  <NA>       2       3
3    B  2001     3       0       1
4    B  2002     4    <NA>    <NA>

In [100]:
l2 = pd.DataFrame([[1 , 2] , [3 , 4] , [5 , 6]] ,
                  index = ['a' , 'c' , 'e'] ,
                  columns = ['A' , 'B'])

In [101]:
l2

   A  B
a  1  2
c  3  4
e  5  6

In [102]:
r2 = pd.DataFrame([[7, 8] , [9 , 10] , [11 , 12] , [13 , 14]] ,
                  index = ['b' , 'c' , 'd' , 'e'] ,
                  columns = ['C' , 'D'])

In [103]:
r2

    C   D
b   7   8
c   9  10
d  11  12
e  13  14

In [104]:
pd.merge(l2 , r2 , how = 'outer' , right_index = True , left_index = True)

     A    B     C     D
a  1.0  2.0   NaN   NaN
b  NaN  NaN   7.0   8.0
c  3.0  4.0   9.0  10.0
d  NaN  NaN  11.0  12.0
e  5.0  6.0  13.0  14.0

In [105]:
l2.join(r2 , how = 'outer')

     A    B     C     D
a  1.0  2.0   NaN   NaN
b  NaN  NaN   7.0   8.0
c  3.0  4.0   9.0  10.0
d  NaN  NaN  11.0  12.0
e  5.0  6.0  13.0  14.0

In [106]:
print('.join instance method to simplify merging by index')

.join instance method to simplify merging by index

In [107]:
l1.join(r1 , on = 'key')

  key  value  group_val
0   a      0        3.5
1   b      1        7.0
2   a      2        3.5
3   a      3        3.5
4   b      4        7.0
5   c      5        NaN

In [108]:
print('By default left join happens in join instance')

By default left join happens in join instance

In [109]:
print('It is more like joining data into the object whose join method is called')

It is more like joining data into the object whose join method is called

In [110]:
another = pd.DataFrame([[7 , 8] , [9 , 10] , [11 , 12] , [16 , 17]] ,
                       index = ['a' , 'c' , 'e' , 'f'] ,
                       columns = ['E' , 'F'])

In [111]:
another

    E   F
a   7   8
c   9  10
e  11  12
f  16  17

In [112]:
l2.join([r2 , another])

     A    B     C     D     E     F
a  1.0  2.0   NaN   NaN   7.0   8.0
c  3.0  4.0   9.0  10.0   9.0  10.0
e  5.0  6.0  13.0  14.0  11.0  12.0

In [113]:
l2.join([r2 , another] , how = 'outer')

     A    B     C     D     E     F
a  1.0  2.0   NaN   NaN   7.0   8.0
c  3.0  4.0   9.0  10.0   9.0  10.0
e  5.0  6.0  13.0  14.0  11.0  12.0
b  NaN  NaN   7.0   8.0   NaN   NaN
d  NaN  NaN  11.0  12.0   NaN   NaN
f  NaN  NaN   NaN   NaN  16.0  17.0

### Concatenating Along An Axis

In [114]:
arr = np.arange(12).reshape((3 , 4))

In [115]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [116]:
np.concatenate([arr , arr] , axis = 1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [117]:
np.concatenate([arr , arr] , axis = 0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [118]:
print('Example with 3 series with no overlapping')

Example with 3 series with no overlapping

In [119]:
s1 = pd.Series([0 , 1] , index = ['a' , 'b'] , dtype = 'Int64')

In [120]:
s2 = pd.Series([2 , 3 , 4] , index = ['c' , 'd' , 'e'] , dtype = 'Int64')

In [121]:
s3 = pd.Series([5 , 6] , index = ['f' , 'g'] , dtype = 'Int64')

In [122]:
pd.concat([s1 , s2 , s3])

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: Int64

In [123]:
pd.concat([s1 , s2 , s3] , axis = 1)

      0     1     2
a     0  <NA>  <NA>
b     1  <NA>  <NA>
c  <NA>     2  <NA>
d  <NA>     3  <NA>
e  <NA>     4  <NA>
f  <NA>  <NA>     5
g  <NA>  <NA>     6

In [124]:
s4 = pd.concat([s1 , s3])

In [125]:
s4

a    0
b    1
f    5
g    6
dtype: Int64

In [126]:
pd.concat([s1 , s4] , axis = 'columns')

      0  1
a     0  0
b     1  1
f  <NA>  5
g  <NA>  6

In [127]:
pd.concat([s1 , s4] , axis = 'columns' , join = 'inner')

   0  1
a  0  0
b  1  1

In [128]:
print('By default the behavior of concat is outer untill specified as this case')

By default the behavior of concat is outer untill specified as this case

In [129]:
print('A potential issue with concatenated pieces is that they are not identifiable is result , we can do heirarchical indexing on axis')

A potential issue with concatenated pieces is that they are not identifiable is result , we can do heirarchical indexing on axis

In [130]:
result = pd.concat([s1 , s2 , s3] , keys = ['one' , 'two' , 'three'])

In [131]:
result

one    a    0
       b    1
two    c    2
       d    3
       e    4
three  f    5
       g    6
dtype: Int64

In [132]:
result.unstack()

          a     b     c     d     e     f     g
one       0     1  <NA>  <NA>  <NA>  <NA>  <NA>
two    <NA>  <NA>     2     3     4  <NA>  <NA>
three  <NA>  <NA>  <NA>  <NA>  <NA>     5     6

In [133]:
pd.concat([s1 , s2 , s3] , axis = 1 , keys = ['one' , 'two' , 'three'])

    one   two  three
a     0  <NA>   <NA>
b     1  <NA>   <NA>
c  <NA>     2   <NA>
d  <NA>     3   <NA>
e  <NA>     4   <NA>
f  <NA>  <NA>      5
g  <NA>  <NA>      6

In [134]:
df1 = pd.DataFrame(np.arange(6).reshape(3,2) ,
                   index = ['a' , 'b' , 'c'] ,
                   columns = ['A' , 'B'])

In [135]:
df1

   A  B
a  0  1
b  2  3
c  4  5

In [136]:
df2 = pd.DataFrame(5 + np.arange(4).reshape(2 , 2) ,
                   index = ['a' , 'c'] ,
                   columns = ['C' , 'D'])

In [137]:
df2

   C  D
a  5  6
c  7  8

In [138]:
pd.concat([df1 , df2] , keys = ['v1' , 'v2'] , axis = 1)

  v1      v2
   A  B    C    D
a  0  1  5.0  6.0
b  2  3  NaN  NaN
c  4  5  7.0  8.0

In [139]:
pd.concat([df1 , df2] , keys = ['v1' , 'v2'] , axis = 1 , names = ['u' , 'l'])

u v1      v2
l  A  B    C    D
a  0  1  5.0  6.0
b  2  3  NaN  NaN
c  4  5  7.0  8.0

In [140]:
print('We can name the levels by using names argument')

We can name the levels by using names argument

In [141]:
df1 = pd.DataFrame(np.random.standard_normal((3 , 4)) , columns = ['a' , 'b' , 'c' , 'd'])

In [142]:
df1

          a         b         c         d
0  1.339407  1.266693 -0.749208  0.847843
1  0.065019 -1.330057 -1.489572 -1.028530
2 -1.076832  0.653389  0.296518 -0.880936

In [143]:
df2 = pd.DataFrame(np.random.normal(0 , 1 , (2 ,3)) , columns = ['b' , 'd' , 'a'])

In [144]:
df2

          b         d         a
0 -0.751687  1.333205 -0.936449
1 -0.723538 -1.068771 -1.205295

In [145]:
print('As the case here the index are not that of significance')

As the case here the index are not that of significance

In [146]:
pd.concat([df1 , df2] , ignore_index = True)

          a         b         c         d
0  1.339407  1.266693 -0.749208  0.847843
1  0.065019 -1.330057 -1.489572 -1.028530
2 -1.076832  0.653389  0.296518 -0.880936
3 -0.936449 -0.751687       NaN  1.333205
4 -1.205295 -0.723538       NaN -1.068771

In [147]:
pd.concat([df1 , df2])

          a         b         c         d
0  1.339407  1.266693 -0.749208  0.847843
1  0.065019 -1.330057 -1.489572 -1.028530
2 -1.076832  0.653389  0.296518 -0.880936
0 -0.936449 -0.751687       NaN  1.333205
1 -1.205295 -0.723538       NaN -1.068771

### Combining Data with Overlap

In [148]:
a = pd.Series([np.nan , 2.5 , 0 , 3.5 , 4.5 , np.nan] , index = ['f' , 'e' , 'd' , 'c' , 'b' , 'a'])

In [149]:
a

f    NaN
e    2.5
d    0.0
c    3.5
b    4.5
a    NaN
dtype: float64

In [150]:
b = pd.Series([0 , np.nan , 2 , np.nan , np.nan , 5] , index = ['a' , 'b' , 'c' , 'd' , 'e' , 'f'])

In [151]:
b

a    0.0
b    NaN
c    2.0
d    NaN
e    NaN
f    5.0
dtype: float64

In [152]:
np.where(pd.isna(a) , b , a)

array([0. , 2.5, 0. , 3.5, 4.5, 5. ])

In [153]:
print('Here our primary objective is to patch the null values in a by non null b values and the index are not aligned by np.where')

Here our primary objective is to patch the null values in a by non null b values and the index are not aligned by np.where

In [154]:
print('Hence for patching combine_first is better')

Hence for patching combine_first is better

In [155]:
a.combine_first(b)

a    0.0
b    4.5
c    3.5
d    0.0
e    2.5
f    5.0
dtype: float64

In [156]:
print('Same patching the missing data happens in DataFrames column by column')

Same patching the missing data happens in DataFrames column by column

In [157]:
df1 = pd.DataFrame({
    'a' : [1 , np.nan , 5 , np.nan] ,
    'b' : [np.nan , 2 , np.nan , 6] ,
    'c' : range(2 , 18 , 4)
})

In [158]:
df2 = pd.DataFrame({
    'a' : [5 , 4 , np.nan , 3 , 7] ,
    'b' : [np.nan , 3 , 4 , 6 , 8]
})

In [159]:
df1

     a    b   c
0  1.0  NaN   2
1  NaN  2.0   6
2  5.0  NaN  10
3  NaN  6.0  14

In [160]:
df2

     a    b
0  5.0  NaN
1  4.0  3.0
2  NaN  4.0
3  3.0  6.0
4  7.0  8.0

In [161]:
df1.combine_first(df2)

     a    b     c
0  1.0  NaN   2.0
1  4.0  2.0   6.0
2  5.0  4.0  10.0
3  3.0  6.0  14.0
4  7.0  8.0   NaN

In [162]:
print('Combine_first will have the union of all the column names')

Combine_first will have the union of all the column names