<a href="https://colab.research.google.com/github/Devil-92/100_Days_of_ML/blob/main/DataCleaning3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

## Categorical Data

In [2]:
values = pd.Series([
    'apple' , 'orange' , 'apple' , 'apple'
] * 2)

In [3]:
values

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
dtype: object

In [4]:
values.unique()

array(['apple', 'orange'], dtype=object)

In [5]:
values.value_counts()

apple     6
orange    2
Name: count, dtype: int64

In [6]:
values = pd.Series([0 , 1 , 0 , 0] * 2)

In [7]:
dim = pd.Series(['apple' , 'orange'])

In [8]:
values

0    0
1    1
2    0
3    0
4    0
5    1
6    0
7    0
dtype: int64

In [9]:
dim

0     apple
1    orange
dtype: object

In [10]:
dim.take(values)

0     apple
1    orange
0     apple
0     apple
0     apple
1    orange
0     apple
0     apple
dtype: object

In [11]:
print('This representation is called categorical or dict encoded where the array of distinct values is called categories and integer values are category codes')

This representation is called categorical or dict encoded where the array of distinct values is called categories and integer values are category codes

In [12]:
fruits = ['apple' , 'orange' , 'apple' , 'apple'] * 2

In [13]:
N = len(fruits)

In [14]:
rng = np.random.default_rng(seed = 42)

In [15]:
df = pd.DataFrame(
    {
        'fruit' : fruits ,
        'basket_id' : np.arange(N) ,
        'count' : rng.integers(3 , 15 , size = N) ,
        'Weight' : rng.uniform(0 , 4 , size = N) ,
    } ,
    columns = ['basket_id' , 'fruit' , 'count' , 'weight']
)

In [16]:
df

   basket_id   fruit  count weight
0          0   apple      4    NaN
1          1  orange     12    NaN
2          2   apple     10    NaN
3          3   apple      8    NaN
4          4   apple      8    NaN
5          5  orange     13    NaN
6          6   apple      4    NaN
7          7   apple     11    NaN

In [17]:
fruit_cat = df['fruit'].astype('category')

In [18]:
fruit_cat

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

In [19]:
c = fruit_cat.array

In [20]:
print(type(c))

<class 'pandas.core.arrays.categorical.Categorical'>

In [21]:
c.categories

Index(['apple', 'orange'], dtype='object')

In [22]:
c.codes

array([0, 1, 0, 0, 0, 1, 0, 0], dtype=int8)

In [23]:
dict(enumerate(c.categories))

{0: 'apple', 1: 'orange'}

In [24]:
df['fruit']

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: object

In [25]:
my_cate = pd.Categorical(['foo' , 'bar' , 'baz' , 'foo' , 'bar'])

In [26]:
my_cate

['foo', 'bar', 'baz', 'foo', 'bar']
Categories (3, object): ['bar', 'baz', 'foo']

In [27]:
dict(enumerate(my_cate.categories))

{0: 'bar', 1: 'baz', 2: 'foo'}

In [28]:
my_cate.codes

array([2, 0, 1, 2, 0], dtype=int8)

In [29]:
cate = ['foo' , 'bar' , 'baz']
codes = [0 , 1 , 2 , 0 , 0 , 1]

In [30]:
my_cate_2 = pd.Categorical.from_codes(codes , cate)

In [31]:
my_cate_2

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo', 'bar', 'baz']

In [32]:
ordered_cat = pd.Categorical.from_codes(codes , cate , ordered = True)

In [33]:
ordered_cat

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo' < 'bar' < 'baz']

In [34]:
my_cate_2.as_ordered()

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo' < 'bar' < 'baz']

In [35]:
print('pd.Categprical.from_codes or just pd.Categorical or astype(Categorical) can be used to form Categorical Data having codes and Categories')

pd.Categprical.from_codes or just pd.Categorical or astype(Categorical) can be used to form Categorical Data having codes and Categories

In [36]:
print('as_ordered() or ordered = True can be used to make them ordered for view and inplace respectively')

as_ordered() or ordered = True can be used to make them ordered for view and inplace respectively

### Computations with Categories

In [37]:
draws = rng.standard_normal(1000)

In [38]:
draws[:5]

array([ 0.0660307 ,  1.12724121,  0.46750934, -0.85929246,  0.36875078])

In [39]:
bins = pd.qcut(draws , 4)

In [40]:
bins

[(0.00618, 0.59], (0.59, 3.179], (0.00618, 0.59], (-3.649, -0.69], (0.00618, 0.59], ..., (-0.69, 0.00618], (0.59, 3.179], (0.00618, 0.59], (-3.649, -0.69], (0.59, 3.179]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.649, -0.69] < (-0.69, 0.00618] < (0.00618, 0.59] <
                                           (0.59, 3.179]]

In [41]:
bins = pd.qcut(draws , 4 , labels = ['Q1' , 'Q2' , 'Q3' , 'Q4'])

In [42]:
bins

['Q3', 'Q4', 'Q3', 'Q1', 'Q3', ..., 'Q2', 'Q4', 'Q3', 'Q1', 'Q4']
Length: 1000
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [43]:
bins.codes[:10]

array([2, 3, 2, 0, 2, 0, 3, 1, 1, 1], dtype=int8)

In [44]:
bins = pd.Series(bins , name = 'quartile')

In [45]:
bins.head()

0    Q3
1    Q4
2    Q3
3    Q1
4    Q3
Name: quartile, dtype: category
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [46]:
results = pd.Series(draws).groupby(bins , observed = False).agg(['count' , 'min' , 'max']).reset_index()

In [47]:
results

  quartile  count       min       max
0       Q1    250 -3.648413 -0.693506
1       Q2    250 -0.688372  0.006017
2       Q3    250  0.006339  0.589547
3       Q4    250  0.590906  3.178854

In [48]:
results['quartile']

0    Q1
1    Q2
2    Q3
3    Q4
Name: quartile, dtype: category
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [49]:
print("The 'quartile' column retains the original categorical info including the ordering")

The 'quartile' column retains the original categorical info including the ordering

#### Better performance with categoricals

In [50]:
n = 10_000_000

In [51]:
labels = pd.Series(['foo' , 'bar' , 'baz' , 'quz'] * int(n/4))

In [52]:
categories = labels.astype('category')

In [53]:
labels.memory_usage(deep = True)

520000132

In [54]:
categories.memory_usage(deep = True)

10000512

In [55]:
print('Categorical Significantly one fifth of default string types')

Categorical Significantly one fifth of default string types

In [56]:
%timeit labels.value_counts()

618 ms ± 7.32 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [57]:
%timeit categories.value_counts()

68.1 ms ± 21.4 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

### Categorical Methods

In [58]:
s = pd.Series(['a' , 'b' , 'c' , 'd'] * 2)

In [59]:
cat_s = s.astype('category')

In [60]:
cat_s

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [61]:
cat_s.cat.codes

0    0
1    1
2    2
3    3
4    0
5    1
6    2
7    3
dtype: int8

In [62]:
cat_s.cat.categories

Index(['a', 'b', 'c', 'd'], dtype='object')

In [63]:
act_cat = ['a' , 'b' , 'c' , 'd' , 'e']

In [64]:
cat_s2 = cat_s.cat.set_categories(act_cat)

In [65]:
cat_s2

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (5, object): ['a', 'b', 'c', 'd', 'e']

In [66]:
cat_s2.value_counts()

a    2
b    2
c    2
d    2
e    0
Name: count, dtype: int64

In [67]:
cat_s.value_counts()

a    2
b    2
c    2
d    2
Name: count, dtype: int64

In [68]:
print('While the data look unchanged the new categories will be reflected in the operations that use them')

While the data look unchanged the new categories will be reflected in the operations that use them

In [69]:
cat_s3 = cat_s[cat_s.isin(['a' , 'b'])]

In [70]:
cat_s3

0    a
1    b
4    a
5    b
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [71]:
cat_s3.cat.categories

Index(['a', 'b', 'c', 'd'], dtype='object')

In [72]:
cat_s3.cat.remove_unused_categories()

0    a
1    b
4    a
5    b
dtype: category
Categories (2, object): ['a', 'b']

In [73]:
cat_s3.cat.categories

Index(['a', 'b', 'c', 'd'], dtype='object')

In [74]:
cat_s3 = cat_s3.cat.add_categories('z')

In [75]:
cat_s3.cat.categories

Index(['a', 'b', 'c', 'd', 'z'], dtype='object')

In [76]:
cat_s3.cat.as_ordered()

0    a
1    b
4    a
5    b
dtype: category
Categories (5, object): ['a' < 'b' < 'c' < 'd' < 'z']

#### Creating Dummy Variable for modelling

In [77]:
cat_s = pd.Series(['a' , 'b' , 'c' , 'd'] * 2 , dtype = 'category')

In [78]:
pd.get_dummies(cat_s)

       a      b      c      d
0   True  False  False  False
1  False   True  False  False
2  False  False   True  False
3  False  False  False   True
4   True  False  False  False
5  False   True  False  False
6  False  False   True  False
7  False  False  False   True