<a href="https://colab.research.google.com/github/Devil-92/100_Days_of_ML/blob/main/FeatureEngineering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



> Feature engineering is one of the most crucial parts of building a good machine
learning model. If we have useful features, the model will perform better. There are
many situations where you can avoid large, complicated models and use simple
models with crucially engineered features. We must keep in mind that feature
engineering is something that is done in the best possible manner only when you
have some knowledge about the domain of the problem and depends a lot on the
data in concern. However, there are some general techniques that you can try to
create features from almost all kinds of numerical and categorical variables.
Feature engineering is not just about creating new features from data but also
includes different types of normalization and transformations.

In [ ]:
import pandas as pd

s = pd.date_range('2026-01-06' , '2026-01-10' , freq = '10h').to_series()

In [ ]:
s

2026-01-06 00:00:00   2026-01-06 00:00:00
2026-01-06 10:00:00   2026-01-06 10:00:00
2026-01-06 20:00:00   2026-01-06 20:00:00
2026-01-07 06:00:00   2026-01-07 06:00:00
2026-01-07 16:00:00   2026-01-07 16:00:00
2026-01-08 02:00:00   2026-01-08 02:00:00
2026-01-08 12:00:00   2026-01-08 12:00:00
2026-01-08 22:00:00   2026-01-08 22:00:00
2026-01-09 08:00:00   2026-01-09 08:00:00
2026-01-09 18:00:00   2026-01-09 18:00:00
Freq: 10h, dtype: datetime64[ns]

In [ ]:
features = {
    'day' : s.dt.day ,
    'month' : s.dt.month ,
    'year' : s.dt.year ,
    'dayofweek' : s.dt.day_of_week ,
    'dayofyear' : s.dt.day_of_week ,
    'hour' : s.dt.hour ,
    'is_leap_year' : s.dt.is_leap_year ,
    'quarter' : s.dt.quarter ,
    'weekofyear' : s.dt.isocalendar().week

}

In [ ]:
features

{'day': 2026-01-06 00:00:00    6
 2026-01-06 10:00:00    6
 2026-01-06 20:00:00    6
 2026-01-07 06:00:00    7
 2026-01-07 16:00:00    7
 2026-01-08 02:00:00    8
 2026-01-08 12:00:00    8
 2026-01-08 22:00:00    8
 2026-01-09 08:00:00    9
 2026-01-09 18:00:00    9
 Freq: 10h, dtype: int32,
 'month': 2026-01-06 00:00:00    1
 2026-01-06 10:00:00    1
 2026-01-06 20:00:00    1
 2026-01-07 06:00:00    1
 2026-01-07 16:00:00    1
 2026-01-08 02:00:00    1
 2026-01-08 12:00:00    1
 2026-01-08 22:00:00    1
 2026-01-09 08:00:00    1
 2026-01-09 18:00:00    1
 Freq: 10h, dtype: int32,
 'year': 2026-01-06 00:00:00    2026
 2026-01-06 10:00:00    2026
 2026-01-06 20:00:00    2026
 2026-01-07 06:00:00    2026
 2026-01-07 16:00:00    2026
 2026-01-08 02:00:00    2026
 2026-01-08 12:00:00    2026
 2026-01-08 22:00:00    2026
 2026-01-09 08:00:00    2026
 2026-01-09 18:00:00    2026
 Freq: 10h, dtype: int32,
 'dayofweek': 2026-01-06 00:00:00    1
 2026-01-06 10:00:00    1
 2026-01-06 20:00:00    1
 2026-01-07 06:00:00    2
 2026-01-07 16:00:00    2
 2026-01-08 02:00:00    3
 2026-01-08 12:00:00    3
 2026-01-08 22:00:00    3
 2026-01-09 08:00:00    4
 2026-01-09 18:00:00    4
 Freq: 10h, dtype: int32,
 'dayofyear': 2026-01-06 00:00:00    1
 2026-01-06 10:00:00    1
 2026-01-06 20:00:00    1
 2026-01-07 06:00:00    2
 2026-01-07 16:00:00    2
 2026-01-08 02:00:00    3
 2026-01-08 12:00:00    3
 2026-01-08 22:00:00    3
 2026-01-09 08:00:00    4
 2026-01-09 18:00:00    4
 Freq: 10h, dtype: int32,
 'hour': 2026-01-06 00:00:00     0
 2026-01-06 10:00:00    10
 2026-01-06 20:00:00    20
 2026-01-07 06:00:00     6
 2026-01-07 16:00:00    16
 2026-01-08 02:00:00     2
 2026-01-08 12:00:00    12
 2026-01-08 22:00:00    22
 2026-01-09 08:00:00     8
 2026-01-09 18:00:00    18
 Freq: 10h, dtype: int32,
 'is_leap_year': 2026-01-06 00:00:00    False
 2026-01-06 10:00:00    False
 2026-01-06 20:00:00    False
 2026-01-07 06:00:00    False
 2026-01-07 16:00:00    False
 2026-01-08 02:00:00    False
 2026-01-08 12:00:00    False
 2026-01-08 22:00:00    False
 2026-01-09 08:00:00    False
 2026-01-09 18:00:00    False
 Freq: 10h, dtype: bool,
 'quarter': 2026-01-06 00:00:00    1
 2026-01-06 10:00:00    1
 2026-01-06 20:00:00    1
 2026-01-07 06:00:00    1
 2026-01-07 16:00:00    1
 2026-01-08 02:00:00    1
 2026-01-08 12:00:00    1
 2026-01-08 22:00:00    1
 2026-01-09 08:00:00    1
 2026-01-09 18:00:00    1
 Freq: 10h, dtype: int32,
 'weekofyear': 2026-01-06 00:00:00    2
 2026-01-06 10:00:00    2
 2026-01-06 20:00:00    2
 2026-01-07 06:00:00    2
 2026-01-07 16:00:00    2
 2026-01-08 02:00:00    2
 2026-01-08 12:00:00    2
 2026-01-08 22:00:00    2
 2026-01-09 08:00:00    2
 2026-01-09 18:00:00    2
 Freq: 10h, Name: week, dtype: UInt32}

> Sometimes, for example, when dealing with time-series problems, you might have
features which are not individual values but a list of values. For example,
transactions by a customer in a given period of time. In these cases, we create
different types of features such as: with numerical features, when you are grouping
on a categorical column, you will get features like a list of values which are time
distributed. In these cases, you can create a bunch of statistical features such as:
- Mean
- Max
- Min
- Unique
- Skew
- Kurtosis
- Kstat
- Percentile
- Quantile
- Peak to peak

The time series data (list of values) can be converted to a lot of features.
A python library called tsfresh is instrumental in this case.

> This is not all; tsfresh offers hundreds of features and tens of variations of different
features that you can use for time series (list of values) based features. In the
examples above, x is a list of values. But that’s not all. There are many other features
that you can create for numerical data with or without categorical data. A simple
way to generate many features is just to create a bunch of polynomial features. For
example, a second-degree polynomial feature from two features “a” and “b” would
include: “a”, “b”, “ab”, “a2” and “b2”.

In [ ]:
import numpy as np

df = pd.DataFrame(
    np.random.rand(100 , 2) ,
    columns = [f"f_{i}" for i in range(1 , 3)]
)

df

         f_1       f_2
0   0.072270  0.907411
1   0.959084  0.988203
2   0.130887  0.143750
3   0.413114  0.504462
4   0.114143  0.410863
..       ...       ...
95  0.498227  0.576118
96  0.646920  0.592640
97  0.638596  0.640127
98  0.483705  0.891077
99  0.040217  0.570270

[100 rows x 2 columns]

In [ ]:
from sklearn import preprocessing

In [ ]:
pf = preprocessing.PolynomialFeatures(
    degree = 2 ,
    interaction_only = False ,
    include_bias = False
)

pf.fit(df)

poly_feats = pf.transform(df)

In [ ]:
poly_feats.shape

(100, 5)

In [ ]:
num_feats = poly_feats.shape[1]

In [ ]:
df_transformed = pd.DataFrame(
    poly_feats ,
    columns = [f'f_{i}' for i in range(1 , num_feats+1)]
)

In [ ]:
df_transformed

         f_1       f_2       f_3       f_4       f_5
0   0.072270  0.907411  0.005223  0.065578  0.823395
1   0.959084  0.988203  0.919843  0.947770  0.976545
2   0.130887  0.143750  0.017132  0.018815  0.020664
3   0.413114  0.504462  0.170663  0.208400  0.254481
4   0.114143  0.410863  0.013029  0.046897  0.168808
..       ...       ...       ...       ...       ...
95  0.498227  0.576118  0.248230  0.287037  0.331912
96  0.646920  0.592640  0.418506  0.383391  0.351222
97  0.638596  0.640127  0.407805  0.408783  0.409762
98  0.483705  0.891077  0.233971  0.431019  0.794019
99  0.040217  0.570270  0.001617  0.022935  0.325208

[100 rows x 5 columns]

> Another interesting feature converts the numbers to categories. It’s known as
binning.

In [ ]:
df['f_bin_10'] = pd.cut(df['f_1'] , bins = 10 , labels = False)
df['f_bin_100'] = pd.cut(df['f_1'] , bins = 100 , labels = False)

In [ ]:
df

         f_1       f_2  f_bin_10  f_bin_100
0   0.072270  0.907411         0          7
1   0.959084  0.988203         9         97
2   0.130887  0.143750         1         13
3   0.413114  0.504462         4         41
4   0.114143  0.410863         1         11
..       ...       ...       ...        ...
95  0.498227  0.576118         5         50
96  0.646920  0.592640         6         65
97  0.638596  0.640127         6         65
98  0.483705  0.891077         4         49
99  0.040217  0.570270         0          3

[100 rows x 4 columns]

In [ ]:
print('Binning also enables u to treat numerical features as categorical')

Binning also enables u to treat numerical features as categorical



> Yet another interesting type of feature that you can create from numerical features
is log transformation.

> Most of the time, these kinds of numerical features are created based on intuition.
There is no formula. If you are working in an industry, you will create your
industry-specific features.

> When dealing with both categorical and numerical variables, you might encounter
missing values.

> For categorical features, let’s keep it super simple. If you ever encounter missing
values in categorical features, treat is as a new category! As simple as this is, it
(almost) always works!

> One way to fill missing values in numerical data would be to choose a value that
does not appear in the specific feature and fill using that. For example, let’s say 0
is not seen in the feature. So, we fill all the missing values using 0. This is one of
the ways but might not be the most effective. One of the methods that works better
than filling 0s for numerical data is to fill with mean instead. You can also try to fill
with the median of all the values for that feature, or you can use the most common
value to fill the missing values. There are just so many ways to do this.

>A fancy way of filling in the missing values would be to use a k-nearest neighbour
method. You can select a sample with missing values and find the nearest
neighbours utilising some kind of distance metric, for example, Euclidean distance.
Then you can take the mean of all nearest neighbours and fill up the missing value.

In [44]:
import numpy as np
from sklearn import impute

X = np.random.randint(1 , 15 , (10 , 6))

X

array([[ 4,  9,  2,  1,  6, 14],
       [ 9,  9, 13,  1,  7,  7],
       [ 9,  4,  2,  5,  1,  7],
       [13,  7, 12, 13,  8,  4],
       [12,  1, 12,  8, 12,  7],
       [ 7, 13, 13,  2,  5, 11],
       [ 4, 12, 13,  6,  1,  8],
       [14, 14, 12, 13, 11,  6],
       [14, 14, 14,  9, 10,  5],
       [14, 13, 13,  1,  6,  9]])

In [45]:
X = X.astype(float)

In [46]:
X

array([[ 4.,  9.,  2.,  1.,  6., 14.],
       [ 9.,  9., 13.,  1.,  7.,  7.],
       [ 9.,  4.,  2.,  5.,  1.,  7.],
       [13.,  7., 12., 13.,  8.,  4.],
       [12.,  1., 12.,  8., 12.,  7.],
       [ 7., 13., 13.,  2.,  5., 11.],
       [ 4., 12., 13.,  6.,  1.,  8.],
       [14., 14., 12., 13., 11.,  6.],
       [14., 14., 14.,  9., 10.,  5.],
       [14., 13., 13.,  1.,  6.,  9.]])

In [47]:
X.ravel()[np.random.choice(X.size , 10 , replace = False)] = np.nan

In [48]:
X

array([[ 4.,  9.,  2., nan,  6., 14.],
       [ 9.,  9., nan,  1.,  7., nan],
       [ 9.,  4.,  2., nan, nan,  7.],
       [13.,  7., 12., 13.,  8.,  4.],
       [12.,  1., 12.,  8., 12.,  7.],
       [ 7., 13., 13.,  2.,  5., nan],
       [ 4., 12., 13.,  6.,  1.,  8.],
       [14., 14., 12., 13., 11., nan],
       [nan, 14., 14.,  9., 10.,  5.],
       [nan, 13., nan,  1.,  6.,  9.]])

In [49]:
knn_imputer = impute.KNNImputer(n_neighbors = 4)

knn_imputer.fit_transform(X)

array([[ 4.  ,  9.  ,  2.  ,  2.5 ,  6.  , 14.  ],
       [ 9.  ,  9.  ,  7.5 ,  1.  ,  7.  ,  9.5 ],
       [ 9.  ,  4.  ,  2.  ,  5.75,  8.25,  7.  ],
       [13.  ,  7.  , 12.  , 13.  ,  8.  ,  4.  ],
       [12.  ,  1.  , 12.  ,  8.  , 12.  ,  7.  ],
       [ 7.  , 13.  , 13.  ,  2.  ,  5.  ,  9.  ],
       [ 4.  , 12.  , 13.  ,  6.  ,  1.  ,  8.  ],
       [14.  , 14.  , 12.  , 13.  , 11.  ,  6.  ],
       [ 9.5 , 14.  , 14.  ,  9.  , 10.  ,  5.  ],
       [ 6.  , 13.  , 10.5 ,  1.  ,  6.  ,  9.  ]])

>Another way of imputing missing values in a column would be to train a regression
model that tries to predict missing values in a column based on other columns. So,
you start with one column that has a missing value and treat this column as the
target column for regression model without the missing values. Using all the other
columns, you now train a model on samples for which there is no missing value in
the concerned column and then try to predict target (the same column) for the
samples that were removed earlier. This way, you have a more robust model based
imputation.

> Always remember that imputing values for tree-based models is unnecessary as they
can handle it themselves

>And always remember to scale or normalize your
features if you are using linear models like logistic regression or a model like SVM.
Tree-based models will always work fine without any normalization of features.