<a href="https://colab.research.google.com/github/Devil-92/100_Days_of_ML/blob/main/MLPP_Murphy__Solution_Chap1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Exercise 1.1 KNN classifier on shuffled MNIST data<br>
Run mnist1NNdemo and verify that the misclassification rate (on the first 1000 test cases) of MNIST of a
1-NN classifier is 3.8%. (If you run it all on all 10,000 test cases, the error rate is 3.09%.) Modify the code
so that you first randomly permute the features (columns of the training and test design matrices), as in
shuffledDigitsDemo, and then apply the classifier. Verify that the error rate is not changed

In [1]:
import pandas as pd
import numpy as np

from sklearn.datasets import fetch_openml

In [2]:
mnist = fetch_openml('mnist_784' , version = 1 , as_frame = True)

In [3]:
X , y = mnist.data , mnist.target

In [4]:
X.shape

(70000, 784)

In [5]:
X.head()

,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,pixel10,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [6]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 1)

In [7]:
X_train = X[:60000]
X_test = X[60000:]

y_train = y[:60000]
y_test = y[60000:]

In [8]:
knn.fit(X_train , y_train)

KNeighborsClassifier(n_neighbors=1)

In [9]:
y_preds = knn.predict(X_test)

In [10]:
from sklearn import metrics

acc = metrics.accuracy_score(y_preds , y_test)

In [11]:
acc

0.9691

In [12]:
misclassification_rate = (1-acc)*100

In [13]:
np.round(misclassification_rate , 2)

np.float64(3.09)

In [14]:
print('Misclassification Rate of 3.09 is verified')

Misclassification Rate of 3.09 is verified

In [15]:
print("Now we will shuffle the dataset")

Now we will shuffle the dataset

In [16]:
X , y = mnist.data , mnist.target

In [17]:
X.head()

,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,pixel10,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [18]:
X = X.sample(frac = 1 , axis = 1)

In [19]:
X.head()

,pixel728,pixel158,pixel402,pixel610,pixel699,pixel92,pixel53,pixel29,pixel670,pixel319,...,pixel375,pixel763,pixel687,pixel683,pixel270,pixel584,pixel691,pixel737,pixel33,pixel237
0,0,136,0,0,0,0,0,0,0,0,...,0,0,0,132,154,0,0,0,0,253
1,0,252,190,0,0,0,0,0,0,253,...,63,0,0,0,228,0,0,0,0,252
2,0,0,47,0,0,0,0,0,0,0,...,0,0,0,0,0,0,254,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,253,251,0,0,0,0,0
4,0,0,30,0,0,0,0,0,0,252,...,0,0,96,0,182,0,0,0,0,232

In [20]:
X_train = X[:60000]
X_test = X[60000:]

y_train = y[:60000]
y_test = y[60000:]

In [21]:
model = KNeighborsClassifier(n_neighbors = 1)

In [22]:
model.fit(X_train , y_train)

KNeighborsClassifier(n_neighbors=1)

In [23]:
y_preds = model.predict(X_test)

In [24]:
acc = metrics.accuracy_score(y_preds , y_test)

In [25]:
acc

0.9691

In [26]:
new_missclassification_rate = (1 - acc)*100

In [27]:
np.round(new_missclassification_rate , 2)

np.float64(3.09)

In [28]:
print('Hence Proved the missclassification rate remains same after shuffling the features or say columns')

Hence Proved the missclassification rate remains same after shuffling the features or say columns